INSERT INTO CLIENTS (NAME, LASTNAME, PROCESSED) VALUES ('Sofia', 'Rojas', False);
INSERT INTO CLIENTS (NAME, LASTNAME, PROCESSED) VALUES ('Maria', 'Mendez', False);
INSERT INTO CLIENTS (NAME, LASTNAME, PROCESSED) VALUES ('Jose', 'Martinez', False);
INSERT INTO CLIENTS (NAME, LASTNAME, PROCESSED) VALUES ('Lorena', 'Camacho', False);
INSERT INTO CLIENTS (NAME, LASTNAME, PROCESSED) VALUES ('Jorge', 'Rodriguez', False);